#!/usr/bin/perl
#
# NodePoint - (C) 2015 Patrick Lambert - http://nodepoint.ca
# Provided under the MIT License
#
# To use on Windows: Change all 'Linux' for 'Win32' in this file.
# To compile into a binary: Use PerlApp with the .perlapp file.
#
package nodepointlc;

# To add a locale:
# - Copy %TMPL to the language you want to add, for example %DE.
# - Each line contains 2 quoted strings. Translate the one on the left to the right.
# - Do not modify the left strings in any way.
# - Do not use any quotes except for notifications.
# - Try to match the punctuation and capitalization as best you can.
# - Add the new language in the lang() function at the bottom.
# - Add the new language to 3 locations in nodepoint.pl (look for 'Default language' and 'Change your language').
# - Download the needed datatables.<lang>.json file from https://www.datatables.net/plug-ins/i18n/

%TMPL =
(
	# Language files
	"datatables.lang.json", "",
	# Labels
	"Home", "",
	"Product", "",
	"Release", "",
	"Model", "",
	"Project", "",
	"Goal", "",
	"Milestone", "",
	"Resource", "",
	"Location", "",
	"Update", "",
	"Application", "",
	"Platform", "",
	"Version", "",
	"Asset", "",
	"Type", "",
	"Instance", "",
	"Tickets", "",
	"Articles", "",
	"Items", "",
	"Clients", "",
	"Settings", "",
	"Statistics", "",
	"Files", "",
	"Automation", "",
	"Custom forms", "",
	"Users management", "",
	"Users", "",
	"System log", "",
	"Logout", "",
	"Ticket ID", "",
	"Open", "",
	"Guest", "",
	"Login", "",
	"Tools", "",
	"Tasks", "",
	"Priority", "",
	# Messages
	"Error", "",
	"Info", "",
	"Success", "",
	"Warning", "",
	# Login page
	"Enter your ", "",
	" credentials.", "",
	"User name must be between 2 and 20 characters.", "",
	"User name", "",
	"Password", "",
	"Register a new account", "",
	"Passwords do not match.", "",
	"Email (optional)", "",
	"Register", "",
	"Forgot your password?", "",
	"Must be a valid email.", "",
	"Please fill out this field.", "",
	"Invalid login credentials.", "",
	# Automation 
	"This module allows you to backup the database along with the uploads folder to another location for safe keeping. The folder must be a local or network path, and the type of backup can be a single archive file or a series of time stamped files.", "",
	"This module can fetch emails from an IMAP account and turn them into tickets automatically. The mail server and inbox information must be provided in order to log in, along with information about the ticket to create, and whether to delete the email afterward.", "",
	"This module will export a specific table to a file location automatically in CSV format. Specify the full path of a local file and the table to export.", "",
	"This module can keep the internal users list in sync with your Active Directory server. This requires credentials of a user with object listing rights. The Base DN should be the OU where your users are kept, and the filter can be used to filter specific object types. Emails can optionally be updated for all users as well.", "",
	"This module will list computer objects from your Active Directory server and create entries in the Inventory Control component. The Base DN should be the OU where your computers are kept. The serial will be set to the machine's hostname. This requires credentials of a user with object listing rights.", "",
	"This module interacts with active tickets that were modified more than x days ago. It can notify assigned users, and close the ticket.", "",
	"This module can remove files uploaded using the Files component after a set amount of days.", "",
	"This module will notify users about expired items checked out, overdue tasks and tickets requiring attention.", "",
	"This module can import CMDB data from a ServiceNow instance and import the data into the Inventory Control component. You need to enter valid credentials and the name of the table to read, along with the table header mappings.", "",
	"This module will dynamically update the MOTD from a text file.", "",
	"<p>Last automation result: <b>", "",
	"The scheduled task <b>nodepoint-automate</b> does not seem to be running. Please check your installation.", "",
	"Automation modules", "",
	"Enabled", "",
	"Disabled", "",
	"5 minutes", "",
	"15 minutes", "",
	"Hourly", "",
	"Daily", "",
	"Weekly", "",
	"Failed", "",
	"Process all modules on next run", "",
	"Automation log", "",
	"All enabled modules will be executed on next run regardless of scheduling.", "",
	"Please wait for this page to reload...", "",
	"Backup folder:", "",
	"Archive type:", "",
	"Export file:", "",
	"Table to export:", "",
	"Text file:", "",
	"Base DN:", "",
	"Filter:", "",
	"Import email addresses:", "",
	"Yes", "",
	"No", "",
	"IMAP Server:", "",
	"IMAP Port:", "",
	"Use SSL:", "",
	"Delete emails:", "",
	"Computer type:", "",
	"Number of days old:", "",
	"Notify assigned users:", "",
	"Close tickets:", "",
	"Expired checkout items:", "",
	"Overdue tasks:", "",
	"Tickets notifications:", "",
	"ServiceNow URL:", "",
	"ServiceNow CMDB table:", "",
	"Asset type:", "",
	"Mapping for 'name':", "",
	"Mapping for 'serial':", "",
	"Mapping for 'info':", "",
	# Notifications
	"This is an automated message from ", "",
	"To disable notifications, log into your account and remove the email under Settings.", "",
	"Could not send notification email to ", "",
	", target email was rejected.", "",
	", connection to SMTP server failed.", "",
	"Email confirmation", "",
	"You are receiving this email because a user was created with this email address. Please confirm your email by logging into the NodePoint interface, and entering the following confirmation code under Settings: ", "",
	"Password reset", "",
	"Your password has been reset by user: ", "",
	"You are receiving this email because a new user was created with this email address. Please confirm your email by logging into the NodePoint interface, and entering the following confirmation code under Settings: ", "",
	# Home page
	"There are ", "",
	" items awaiting checkout approval. Press <a href='./?m=items'>here</a> to view the list.", "",
	"Clear", "",
	"Ticket", "",
	"requires your attention.", "",
	"Getting started", "",
	"<p>Use the <b>", "",
	"s</b> tab to browse available ", "",
	"s along with their ", "",
	"s. You can view basic information about them and see their description.", "",
	" Use the <b>Tickets</b> tab to browse current tickets and comments.", "",
	" The <b>Articles</b> tab contains related support articles.", "",
	" The <b>Items</b> tab contains inventory items you can checkout.", "",
	" The <b>Clients</b> tab contains a list of contacts.", "",
	" You can also change your email address and password under the <b>Settings</b> tab.</p>", "",
	"Your current access level is", "",
	"<p>Your email address is not currently confirmed. Make sure you go to the Settings tab to enter your confirmation code. You can also change your email address if you did not receive your confirmation email.</p>", "",
	"Shoutbox", "",
	"Type your message here", "",
	"Tickets you created", "",
	"Tickets you follow", "",
	"Tickets assigned to you", "",
	"Tasks assigned to you", "",
	"Subscribed articles", "",
	"Checked out items", "",
	"Waiting approval", "",
	"Logged in successfully.", "",
	"Logged in successfully. Your last login was on ", "",
	# Table headers
	"ID", "",
	"Title", "",
	"Status", "",
	"Last modified", "",
	"High", "",
	"Low", "",
	"Normal", "",
	"Task", "",
	"Due by", "",
	"Completion", "",
	"Completed", "",
	"Overdue", "",
	"Type", "",
	"Name", "",
	"Serial", "",
	"File name", "",
	"File size", "",
	"Uploaded by", "",
	"Date", "",
	"Hits", "",
	"Download link", "",
	"IP address", "",
	"Schedule", "",
	"Last run time", "",
	"Last result", "",
	"Module", "",
	"Email", "",
	"Level", "",
	"Last login", "",
	# Settings
	"<p>You are logged in as <b>", "",
	"</b> and your access level is <b>", "",
	"<p>You have spent a total of <b>", "",
	"</b> hours on tickets.</p>", "",
	"Your email is not yet confirmed. Please enter the confirmation code here:", "",
	"Email notifications are disabled.", "",
	"Change your email", "",
	"To change your notification email address, enter a new address here. Leave empty to disable notifications:", "",
	"Must be a valid email.", "",
	"Email address", "",
	"Change email", "",
	"Change your language", "",
	"Select your language:", "",
	"Change language", "",
	"Change your password", "",
	"<p>Password management is synchronized with Active Directory.</p>", "",
	"<p>The demo account cannot change its password.</p>", "",
	"Current password", "",
	"New password", "",
	"Passwords do not match.", "",
	"Change password", "",
	"Email address confirmed. Press <a href='.'>here</a> to continue.", "",
	"Confirmation code not found. Please go back and try again.", "",
	"Email address updated. Press <a href='.'>here</a> to continue.", "",
	"Password changed. Press <a href='.'>here</a> to go back home.", "",
	# Users
	"You have now logged out. Press <a href='.'>here</a> to go back to the login page.", "",
	"Invalid access level. Please go back and try again.", "",
	"Updated access level for user <b>", "",
	"</b>. Press <a href='./?m=users'>here</a> to continue.", "",
	"Level change: ", "",
	"Select a new access level for user <b>", "",
	"<p>Here is a list of available NodePoint levels:</p>", "",
	"Can change basic NodePoint settings", "",
	"Can manage users, reset passwords, edit clients", "",
	"Can add, retire and edit ", "",
	"s, edit articles and items", "",
	"Can create ", "",
	"s, update tickets, track time", "",
	"Can view restricted tickets and ", "",
	"Can create tickets and comments", "",
	"Can view private tickets", "",
	"Password reset for user <b>", "",
	"</b>. The new password is <b>", "",
	"</b>. Press <a href='./?m=users'>here</a> to continue." ,"",
	"Add a new user:", "",
	"Passwords do not match. Please go back and try again.", "",
	"This user name is reserved. Please go back and try again.", "",
	"User names should be between 3 and 20 characters, passwords should be at least 6 characters, emails less than 99 characters. Please go back and try again.", "",
	"User <b>", "",
	"</b> added. Press <a href='./?m=users'>here</a> to continue.", "",
	"</b> added. Press <a href='.'>here</a> to go to the login page.", "",
	"User already exists. Please go back and try again.", "",
	# Files
	"File not found or corrupted.", "",
	"File size is larger than accepted value.", "",
	"File <b>", "",
	"</b> uploaded.", "",
	"File uploading to <b>", "",
	"</b> failed.", "",
	"Add a new file", "",
	"Available files", "",
	"Access log", "",
	"Select a file", "",
	# Items
	"Require checkout approval", "",
	"Desktop", "",
	"Laptop", "",
	"Server", "",
	"Keyboard", "",
	"Mouse", "",
	"Display", "",
	"Phone", "",
	"Software", "",
	"Printer", "",
	"Peripheral", "",
	"Furniture", "",
	"Tool", "",
	"Other", "",
	# Buttons
	"Post", "",
	"Save", "",
	"Confirm", "",
	"Upload", "",
	"Clear log", "",
	"Reset modules", "",
	"Add user", "",
);

%EN =
(
	# Language files
	"datatables.lang.json", "datatables.en.json",
	# Labels
	"Home", "Home",
	"Product", "Product",
	"Release", "Release",
	"Model", "Model",
	"Project", "Project",
	"Goal", "Goal",
	"Milestone", "Milestone",
	"Resource", "Resource",
	"Location", "Location",
	"Update", "Update",
	"Application", "Application",
	"Platform", "Platform",
	"Version", "Version",
	"Asset", "Asset",
	"Type", "Type",
	"Instance", "Instance",
	"Tickets", "Tickets",
	"Articles", "Articles",
	"Items", "Items",
	"Clients", "Clients",
	"Settings", "Settings",
	"Statistics", "Statistics",
	"Files", "Files",
	"Automation", "Automation",
	"Custom forms", "Custom forms",
	"Users management", "Users management",
	"Users", "Users",
	"System log", "System log",
	"Logout", "Logout",
	"Ticket ID", "Ticket ID",
	"Open", "Open",
	"Guest", "Guest",
	"Login", "Login",
	"Tools", "Tools",
	"Tasks", "Tasks",
	"Priority", "Priority",
	# Messages
	"Error", "Error",
	"Info", "Info",
	"Success", "Success",
	"Warning", "Warning",
	# Login page
	"Enter your ", "Enter your ",
	" credentials.", " credentials.",
	"User name must be between 2 and 20 characters.", "User name must be between 2 and 20 characters.",
	"User name", "User name",
	"Password", "Password",
	"Register a new account", "Register a new account",
	"Passwords do not match.", "Passwords do not match.",
	"Email (optional)", "Email (optional)",
	"Register", "Register",
	"Forgot your password?", "Forgot your password?",
	"Must be a valid email.", "Must be a valid email.",
	"Please fill out this field.", "Please fill out this field.",
	"Invalid login credentials.", "Invalid login credentials.",
	# Automation 
	"This module allows you to backup the database along with the uploads folder to another location for safe keeping. The folder must be a local or network path, and the type of backup can be a single archive file or a series of time stamped files.", "This module allows you to backup the database along with the uploads folder to another location for safe keeping. The folder must be a local or network path, and the type of backup can be a single archive file or a series of time stamped files.",
	"This module can fetch emails from an IMAP account and turn them into tickets automatically. The mail server and inbox information must be provided in order to log in, along with information about the ticket to create, and whether to delete the email afterward.", "This module can fetch emails from an IMAP account and turn them into tickets automatically. The mail server and inbox information must be provided in order to log in, along with information about the ticket to create, and whether to delete the email afterward.",
	"This module will export a specific table to a file location automatically in CSV format. Specify the full path of a local file and the table to export.", "This module will export a specific table to a file location automatically in CSV format. Specify the full path of a local file and the table to export.",
	"This module can keep the internal users list in sync with your Active Directory server. This requires credentials of a user with object listing rights. The Base DN should be the OU where your users are kept, and the filter can be used to filter specific object types. Emails can optionally be updated for all users as well.", "This module can keep the internal users list in sync with your Active Directory server. This requires credentials of a user with object listing rights. The Base DN should be the OU where your users are kept, and the filter can be used to filter specific object types. Emails can optionally be updated for all users as well.",
	"This module will list computer objects from your Active Directory server and create entries in the Inventory Control component. The Base DN should be the OU where your computers are kept. The serial will be set to the machine's hostname. This requires credentials of a user with object listing rights.", "This module will list computer objects from your Active Directory server and create entries in the Inventory Control component. The Base DN should be the OU where your computers are kept. The serial will be set to the machine's hostname. This requires credentials of a user with object listing rights.",
	"This module interacts with active tickets that were modified more than x days ago. It can notify assigned users, and close the ticket.", "This module interacts with active tickets that were modified more than x days ago. It can notify assigned users, and close the ticket.",
	"This module can remove files uploaded using the Files component after a set amount of days.", "This module can remove files uploaded using the Files component after a set amount of days.",
	"This module will notify users about expired items checked out, overdue tasks and tickets requiring attention.", "This module will notify users about expired items checked out, overdue tasks and tickets requiring attention.",
	"This module can import CMDB data from a ServiceNow instance and import the data into the Inventory Control component. You need to enter valid credentials and the name of the table to read, along with the table header mappings.", "This module can import CMDB data from a ServiceNow instance and import the data into the Inventory Control component. You need to enter valid credentials and the name of the table to read, along with the table header mappings.",
	"This module will dynamically update the MOTD from a text file.", "This module will dynamically update the MOTD from a text file.",
	"<p>Last automation result: <b>", "<p>Last automation result: <b>",
	"The scheduled task <b>nodepoint-automate</b> does not seem to be running. Please check your installation.", "The scheduled task <b>nodepoint-automate</b> does not seem to be running. Please check your installation.",
	"Automation modules", "Automation modules",
	"Enabled", "Enabled",
	"Disabled", "Disabled",
	"5 minutes", "5 minutes",
	"15 minutes", "15 minutes",
	"Hourly", "Hourly",
	"Daily", "Daily",
	"Weekly", "Weekly",
	"Failed", "Failed",
	"Process all modules on next run", "Process all modules on next run",
	"Automation log", "Automation log",
	"All enabled modules will be executed on next run regardless of scheduling.", "All enabled modules will be executed on next run regardless of scheduling.",
	"Please wait for this page to reload...", "Please wait for this page to reload...",
	"Backup folder:", "Backup folder:",
	"Archive type:", "Archive type:",
	"Export file:", "Export file:",
	"Table to export:", "Table to export:",
	"Text file:", "Text file:",
	"Base DN:", "Base DN:",
	"Filter:", "Filter:",
	"Import email addresses:", "Import email addresses:",
	"Yes", "Yes",
	"No", "No",
	"IMAP Server:", "IMAP Server:",
	"IMAP Port:", "IMAP Port:",
	"Use SSL:", "Use SSL:",
	"Delete emails:", "Delete emails:",
	"Computer type:", "Computer type:",
	"Number of days old:", "Number of days old:",
	"Notify assigned users:", "Notify assigned users:",
	"Close tickets:", "Close tickets:",
	"Expired checkout items:", "Expired checkout items:",
	"Overdue tasks:", "Overdue tasks:",
	"Tickets notifications:", "Tickets notifications:",
	"ServiceNow URL:", "ServiceNow URL:",
	"ServiceNow CMDB table:", "ServiceNow CMDB table:",
	"Asset type:", "Asset type:",
	"Mapping for 'name':", "Mapping for 'name':",
	"Mapping for 'serial':", "Mapping for 'serial':",
	"Mapping for 'info':", "Mapping for 'info':",
	# Notifications
	"This is an automated message from ", "This is an automated message from ",
	"To disable notifications, log into your account and remove the email under Settings.", "To disable notifications, log into your account and remove the email under Settings.",
	"Could not send notification email to ", "Could not send notification email to ",
	", target email was rejected.", ", target email was rejected.",
	", connection to SMTP server failed.", ", connection to SMTP server failed.",
	"Email confirmation", "Email confirmation",
	"You are receiving this email because a user was created with this email address. Please confirm your email by logging into the NodePoint interface, and entering the following confirmation code under Settings: ", "You are receiving this email because a user was created with this email address. Please confirm your email by logging into the NodePoint interface, and entering the following confirmation code under Settings: ",
	"Password reset", "Password reset",
	"Your password has been reset by user: ", "Your password has been reset by user: ",
	"You are receiving this email because a new user was created with this email address. Please confirm your email by logging into the NodePoint interface, and entering the following confirmation code under Settings: ", "You are receiving this email because a new user was created with this email address. Please confirm your email by logging into the NodePoint interface, and entering the following confirmation code under Settings: ",
	# Home page
	"There are ", "There are ",
	" items awaiting checkout approval. Press <a href='./?m=items'>here</a> to view the list.", " items awaiting checkout approval. Press <a href='./?m=items'>here</a> to view the list.",
	"Clear", "Clear",
	"Ticket", "Ticket",
	"requires your attention.", "requires your attention.",
	"Getting started", "Getting started",
	"<p>Use the <b>", "<p>Use the <b>",
	"s</b> tab to browse available ", "s</b> tab to browse available ",
	"s along with their ", "s along with their ",
	"s. You can view basic information about them and see their description.", "s. You can view basic information about them and see their description.",
	" Use the <b>Tickets</b> tab to browse current tickets and comments.", " Use the <b>Tickets</b> tab to browse current tickets and comments.",
	" The <b>Articles</b> tab contains related support articles.", " The <b>Articles</b> tab contains related support articles.",
	" The <b>Items</b> tab contains inventory items you can checkout.", " The <b>Items</b> tab contains inventory items you can checkout.",
	" The <b>Clients</b> tab contains a list of contacts.", " The <b>Clients</b> tab contains a list of contacts.",
	" You can also change your email address and password under the <b>Settings</b> tab.</p>", " You can also change your email address and password under the <b>Settings</b> tab.</p>",
	"Your current access level is", "Your current access level is",
	"<p>Your email address is not currently confirmed. Make sure you go to the Settings tab to enter your confirmation code. You can also change your email address if you did not receive your confirmation email.</p>", "<p>Your email address is not currently confirmed. Make sure you go to the Settings tab to enter your confirmation code. You can also change your email address if you did not receive your confirmation email.</p>",
	"Shoutbox", "Shoutbox",
	"Type your message here", "Type your message here",
	"Tickets you created", "Tickets you created",
	"Tickets you follow", "Tickets you follow",
	"Tickets assigned to you", "Tickets assigned to you",
	"Tasks assigned to you", "Tasks assigned to you",
	"Subscribed articles", "Subscribed articles",
	"Checked out items", "Checked out items",
	"Waiting approval", "Waiting approval",
	"Logged in successfully.", "Logged in successfully.",
	"Logged in successfully. Your last login was on ", "Logged in successfully. Your last login was on ",
	# Table headers
	"ID", "ID",
	"Title", "Title",
	"Status", "Status",
	"Last modified", "Last modified",
	"High", "High",
	"Low", "Low",
	"Normal", "Normal",
	"Task", "Task",
	"Due by", "Due by",
	"Completion", "Completion",
	"Completed", "Completed",
	"Overdue", "Overdue",
	"Type", "Type",
	"Name", "Name",
	"Serial", "Serial",
	"File name", "File name",
	"File size", "File size",
	"Uploaded by", "Uploaded by",
	"Date", "Date",
	"Hits", "Hits",
	"Download link", "Download link",
	"IP address", "IP address",
	"Schedule", "Schedule",
	"Last run time", "Last run time",
	"Last result", "Last result",
	"Module", "Module",
	"Email", "Email",
	"Level", "Level",
	"Last login", "Last login",
	# Settings
	"<p>You are logged in as <b>", "<p>You are logged in as <b>",
	"</b> and your access level is <b>", "</b> and your access level is <b>",
	"<p>You have spent a total of <b>", "<p>You have spent a total of <b>",
	"</b> hours on tickets.</p>", "</b> hours on tickets.</p>",
	"Your email is not yet confirmed. Please enter the confirmation code here:", "Your email is not yet confirmed. Please enter the confirmation code here:",
	"Email notifications are disabled.", "Email notifications are disabled.",
	"Change your email", "Change your email",
	"To change your notification email address, enter a new address here. Leave empty to disable notifications:", "To change your notification email address, enter a new address here. Leave empty to disable notifications:",
	"Must be a valid email.", "Must be a valid email.",
	"Email address", "Email address",
	"Change email", "Change email",
	"Change your language", "Change your language",
	"Select your language:", "Select your language:",
	"Change language", "Change language",
	"Change your password", "Change your password",
	"<p>Password management is synchronized with Active Directory.</p>", "<p>Password management is synchronized with Active Directory.</p>",
	"<p>The demo account cannot change its password.</p>", "<p>The demo account cannot change its password.</p>",
	"Current password", "Current password",
	"New password", "New password",
	"Passwords do not match.", "Passwords do not match.",
	"Change password", "Change password",
	"Email address confirmed. Press <a href='.'>here</a> to continue.", "Email address confirmed. Press <a href='.'>here</a> to continue.",
	"Confirmation code not found. Please go back and try again.", "Confirmation code not found. Please go back and try again.",
	"Email address updated. Press <a href='.'>here</a> to continue.", "Email address updated. Press <a href='.'>here</a> to continue.",
	"Password changed. Press <a href='.'>here</a> to go back home.", "Password changed. Press <a href='.'>here</a> to go back home.",
	# Users
	"You have now logged out. Press <a href='.'>here</a> to go back to the login page.", "You have now logged out. Press <a href='.'>here</a> to go back to the login page.",
	"Invalid access level. Please go back and try again.", "Invalid access level. Please go back and try again.",
	"Updated access level for user <b>", "Updated access level for user <b>",
	"</b>. Press <a href='./?m=users'>here</a> to continue.", "</b>. Press <a href='./?m=users'>here</a> to continue.",
	"Level change: ", "Level change: ",
	"Select a new access level for user <b>", "Select a new access level for user <b>",
	"<p>Here is a list of available NodePoint levels:</p>", "<p>Here is a list of available NodePoint levels:</p>",
	"Can change basic NodePoint settings", "Can change basic NodePoint settings",
	"Can manage users, reset passwords, edit clients", "Can manage users, reset passwords, edit clients",
	"Can add, retire and edit ", "Can add, retire and edit ",
	"s, edit articles and items", "s, edit articles and items",
	"Can create ", "Can create ",
	"s, update tickets, track time", "s, update tickets, track time",
	"Can view restricted tickets and ", "Can view restricted tickets and ",
	"Can create tickets and comments", "Can create tickets and comments",
	"Can view private tickets", "Can view private tickets",
	"Password reset for user <b>", "Password reset for user <b>",
	"</b>. The new password is <b>", "</b>. The new password is <b>",
	"</b>. Press <a href='./?m=users'>here</a> to continue.", "</b>. Press <a href='./?m=users'>here</a> to continue.",
	"Add a new user:", "Add a new user:",
	"Passwords do not match. Please go back and try again.", "Passwords do not match. Please go back and try again.",
	"This user name is reserved. Please go back and try again.", "This user name is reserved. Please go back and try again.",
	"User names should be between 3 and 20 characters, passwords should be at least 6 characters, emails less than 99 characters. Please go back and try again.", "User names should be between 3 and 20 characters, passwords should be at least 6 characters, emails less than 99 characters. Please go back and try again.",
	"User <b>", "User <b>",
	"</b> added. Press <a href='./?m=users'>here</a> to continue.", "</b> added. Press <a href='./?m=users'>here</a> to continue.",
	"</b> added. Press <a href='.'>here</a> to go to the login page.", "</b> added. Press <a href='.'>here</a> to go to the login page.",
	"User already exists. Please go back and try again.", "User already exists. Please go back and try again.",
	# Files
	"File not found or corrupted.", "File not found or corrupted.",
	"File size is larger than accepted value.", "File size is larger than accepted value.",
	"File <b>", "File <b>",
	"</b> uploaded.", "</b> uploaded.",
	"File uploading to <b>", "File uploading to <b>",
	"</b> failed.", "</b> failed.",
	"Add a new file", "Add a new file",
	"Available files", "Available files",
	"Access log", "Access log",
	"Select a file", "Select a file",
	# Items
	"Require checkout approval", "Require checkout approval",
	"Desktop", "Desktop",
	"Laptop", "Laptop",
	"Server", "Server",
	"Keyboard", "Keyboard",
	"Mouse", "Mouse",
	"Display", "Display",
	"Phone", "Phone",
	"Software", "Software",
	"Printer", "Printer",
	"Peripheral", "Peripheral",
	"Furniture", "Furniture",
	"Tool", "Tool",
	"Other", "Other",
	# Buttons
	"Post", "Post",
	"Save", "Save",
	"Confirm", "Confirm",
	"Upload", "Upload",
	"Clear log", "Clear log",
	"Reset modules", "Reset modules",
	"Add user", "Add user",
);

%FR =
(
	# Language files
	"datatables.lang.json", "datatables.fr.json",
	# Labels
	"Home", "Accueil",
	"Product", "Produit",
	"Release", "Version",
	"Model", "Modèle",
	"Project", "Projet",
	"Goal", "Objectif",
	"Milestone", "Étape",
	"Resource", "Ressource",
	"Location", "Emplacement",
	"Update", "Mise à jour",
	"Application", "Application",
	"Platform", "Plate-forme",
	"Version", "Version",
	"Asset", "Atout",
	"Type", "Genre",
	"Instance", "Article",
	"Tickets", "Billets",
	"Articles", "Articles",
	"Items", "Objets",
	"Clients", "Clients",
	"Settings", "Préférences",
	"Statistics", "Statistiques",
	"Files", "Fichiers",
	"Automation", "Automatisation",
	"Custom forms", "Formulaires personnalisés",
	"Users management", "Utilisateurs",
	"Users", "Utilisateurs",
	"System log", "Journal du système",
	"Logout", "Se déconnecter",
	"Ticket ID", "Billet ID",
	"Open", "Ouvrir",
	"Guest", "Invité",
	"Login", "Identification",
	"Tools", "Outils",
	"Tasks", "Tâches",
	"Priority", "Priorité",
	# Messages
	"Error", "Erreur",
	"Info", "Info",
	"Success", "Succès",
	"Warning", "Attention",
	# Login page
	"Enter your ", "Entrez vos informations d&apos;identification pour ",
	" credentials.", ".",
	"User name must be between 2 and 20 characters.", "Nom d&apos;utilisateur doit être entre 2 et 20 caractères.",
	"User name", "Nom d&apos;utilisateur",
	"Password", "Mot de passe",
	"Register a new account", "Créer un nouveau compte",
	"Passwords do not match.", "Les mots de passe ne correspondent pas.",
	"Email (optional)", "Email (facultatif)",
	"Register", "Créer",
	"Forgot your password?", "Mot de passe oublié?",
	"Must be a valid email.", "Doit être une adresse email valide",
	"Please fill out this field.", "S&apos;il vous plaît remplir ce champ",
	"Invalid login credentials.", "Authentification invalide.",
	# Automation 
	"This module allows you to backup the database along with the uploads folder to another location for safe keeping. The folder must be a local or network path, and the type of backup can be a single archive file or a series of time stamped files.", "Ce module vous permet de sauvegarder la base de données ainsi que le dossier de fichiers vers un autre emplacement. Le dossier doit être un chemin local ou réseau, et le type de sauvegarde peut être un seul fichier d'archive ou une série de fichiers horodatés.",
	"This module can fetch emails from an IMAP account and turn them into tickets automatically. The mail server and inbox information must be provided in order to log in, along with information about the ticket to create, and whether to delete the email afterward.", "Ce module peut aller chercher des emails à partir d'un compte IMAP et les transforme en billets automatiquement. Les informations du serveur de messagerie et boîte de réception doivent être fournis afin de se connecter, avec les informations sur les billets de créer.",
	"This module will export a specific table to a file location automatically in CSV format. Specify the full path of a local file and the table to export.", "Ce module va exporter une table spécifique à un emplacement de fichier automatiquement en format CSV. Indiquez le chemin complet d'un fichier local et la table à exporter.",
	"This module can keep the internal users list in sync with your Active Directory server. This requires credentials of a user with object listing rights. The Base DN should be the OU where your users are kept, and the filter can be used to filter specific object types. Emails can optionally be updated for all users as well.", "Ce module peut garder la liste des utilisateurs internes en phase avec votre serveur Active Directory. Cela nécessite les informations d'identification d'un utilisateur avec la permission d'énumérer les objets. Le DN de base doit être l'unité d'organisation où vos utilisateurs sont conservées, et le filtre peut être utilisé pour filtrer un spécifique type d'objets. les emails peuvent aussi être mis à jour pour tous les utilisateurs.",
	"This module will list computer objects from your Active Directory server and create entries in the Inventory Control component. The Base DN should be the OU where your computers are kept. The serial will be set to the machine's hostname. This requires credentials of a user with object listing rights.", "Ce module liste des objets ordinateur à partir de votre serveur Active Directory et crée des entrées dans le composant de gestion des objets. Le DN de base doit être l'unité d'organisation où vos ordinateurs sont conservés. Le numéro de série sera réglé sur le nom d'hôte de la machine. Cela nécessite les informations d'identification d'un utilisateur avec la permission d'énumérer les objets.",
	"This module interacts with active tickets that were modified more than x days ago. It can notify assigned users, and close the ticket.", "Ce module interagit avec billets actifs qui ont été modifiés il y a plus x jours. Il peut avertir les utilisateurs affectés, et fermer le billet.",
	"This module can remove files uploaded using the Files component after a set amount of days.", "Ce module peut supprimer les fichiers téléchargés en utilisant le composant Fichiers après un certain laps de jours.",
	"This module will notify users about expired items checked out, overdue tasks and tickets requiring attention.", "Ce module informera les utilisateurs sur les produits périmés, les tâches et les billets en retard nécessitant une attention particulière.",
	"This module can import CMDB data from a ServiceNow instance and import the data into the Inventory Control component. You need to enter valid credentials and the name of the table to read, along with the table header mappings.", "Ce module peut importer des données CMDB d'une instance ServiceNow et importer les données dans le composant de gestion des objets. Vous devez entrer les informations d'identification valides et le nom de la table à lire, avec l'en-tête de table correspondantes.",
	"This module will dynamically update the MOTD from a text file.", "Ce module va mettre à jour dynamiquement le MOTD à partir d'un fichier texte.",
	"<p>Last automation result: <b>", "<p>Résultat de la dernière automatisation: <b>",
	"The scheduled task <b>nodepoint-automate</b> does not seem to be running. Please check your installation.", "La tâche planifiée <b>nodepoint-automate</b> ne semble pas être en cours d'exécution. S'il vous plaît vérifier votre installation.",
	"Automation modules", "Modules d'automatisation",
	"Enabled", "Activé",
	"Disabled", "Désactivée",
	"5 minutes", "5 minutes",
	"15 minutes", "15 minutes",
	"Hourly", "Une fois par heure",
	"Daily", "Une fois par jour",
	"Weekly", "Une fois par semaine",
	"Failed", "Échoué",
	"Process all modules on next run", "Traiter tous les modules à la prochaine exécution.",
	"Automation log", "Journal d'automatisation",
	"All enabled modules will be executed on next run regardless of scheduling.", "Tous les modules activés seront exécutés à la prochaine exécution.",
	"Please wait for this page to reload...", "S'il vous plaît attendre que cette page recharge...",
	"Backup folder:", "Dossier de sauvegarde:",
	"Archive type:", "Type de sauvegarde:",
	"Export file:", "Ficher d'exportation:",
	"Table to export:", "Table à exporter:",
	"Text file:", "Fichier text:",
	"Base DN:", "Base DN:",
	"Filter:", "Filtre:",
	"Import email addresses:", "Importer les adresses email:",
	"Yes", "Oui",
	"No", "Non",
	"IMAP Server:", "Serveur IMAP:",
	"IMAP Port:", "Port IMAP:",
	"Use SSL:", "Cryptage SSL:",
	"Delete emails:", "Supprimer les emails:",
	"Computer type:", "Type d'ordinateur:",
	"Number of days old:", "Nombre de jours:",
	"Notify assigned users:", "Informer les utilisateurs assignés:",
	"Close tickets:", "Fermer les billets:",
	"Expired checkout items:", "Objets expirés:",
	"Overdue tasks:", "Tâches en retard:",
	"Tickets notifications:", "Notifications de billets:",
	"ServiceNow URL:", "Adresse ServiceNow:",
	"ServiceNow CMDB table:", "Table CMDB:",
	"Asset type:", "Type d'objects:",
	"Mapping for 'name':", "Plan pour 'nom':",
	"Mapping for 'serial':", "Plan pour 'num. de série':",
	"Mapping for 'info':", "Plan pour 'info':",
	# Notifications
	"This is an automated message from ", "Ceci est un message automatique de ",
	"To disable notifications, log into your account and remove the email under Settings.", "Pour désactiver les notifications, connectez-vous à votre compte et supprimer l'email sous Paramètres.",
	"Could not send notification email to ", "Impossible d'envoyer une notification email à ",
	", target email was rejected.", ", le email a été rejeté.",
	", connection to SMTP server failed.", ", la connexion au serveur SMTP a échoué.",
	"Email confirmation", "Confirmation email",
	"You are receiving this email because a user was created with this email address. Please confirm your email by logging into the NodePoint interface, and entering the following confirmation code under Settings: ", "Vous recevez ce email car un utilisateur a été créé à cette adresse e-mail. S'il vous plaît confirmer votre email en vous connectant à l'interface NodePoint, et en entrant le code de confirmation suivant sous Paramètres: ",
	"Password reset", "Changement de mot de passe",
	"Your password has been reset by user: ", "Votre mot de passe a été réinitialisé par l'utilisateur: ",
	"You are receiving this email because a new user was created with this email address. Please confirm your email by logging into the NodePoint interface, and entering the following confirmation code under Settings: ", "Vous recevez ce email car un nouvel utilisateur a été créé à cette adresse e-mail. S'il vous plaît confirmer votre email en vous connectant à l'interface NodePoint, et en entrant le code de confirmation suivant sous Paramètres: ",
	# Home page
	"There are ", "Il y a ",
	" items awaiting checkout approval. Press <a href='./?m=items'>here</a> to view the list.", " objets en attente d&apos;approbation. Appuyez <a href='./?m=items'>ici</a> pour afficher la liste.",
	"Clear", "Enlever",
	"Ticket", "Billet",
	"requires your attention.", "exige votre attention.",
	"Getting started", "Message de bienvenue",
	"<p>Use the <b>", "<p>Utilisez l&apos;onglet <b>",
	"s</b> tab to browse available ", "s</b> pour voir les ",
	"s along with their ", "s avec leurs ",
	"s. You can view basic information about them and see their description.", "s. Vous pouvez afficher des informations de base sur eux et voir leur description.",
	" Use the <b>Tickets</b> tab to browse current tickets and comments.", " Utilisez l&apos;onglet <b>Billets</b> pour parcourir les billets et commentaires.",
	" The <b>Articles</b> tab contains related support articles.", " L&apos;onglet <b>Articles</b> contient des articles connexes de soutien.",
	" The <b>Items</b> tab contains inventory items you can checkout.", " L&apos;onglet <b>Objets</b> contient des éléments d'inventaire que vous pouvez demander.",
	" The <b>Clients</b> tab contains a list of contacts.", " L&apos;onglet <b>Clients</b> contient la liste des contacts.",
	" You can also change your email address and password under the <b>Settings</b> tab.</p>", " Vous pouvez également modifier votre adresse email et mot de passe dans <b>Paramètres</b>.</p>",
	"Your current access level is", "Votre niveau d&apos;accès actuel est",
	"<p>Your email address is not currently confirmed. Make sure you go to the Settings tab to enter your confirmation code. You can also change your email address if you did not receive your confirmation email.</p>", "<p>Votre adresse de messagerie n&apos;est pas confirmée. Assurez-vous que vous allez à l'onglet Paramètres pour entrer votre code de confirmation. Vous pouvez également modifier votre adresse email si vous ne recevez pas votre courriel de confirmation.</p>",
	"Shoutbox", "Shoutbox",
	"Type your message here", "Entrez votre message ici",
	"Tickets you created", "Billets que vous avez créé",
	"Tickets you follow", "Billets suivies",
	"Tickets assigned to you", "Billets qui vous sont assignées",
	"Tasks assigned to you", "Tâches qui vous sont assignées",
	"Subscribed articles", "Articles souscrit",
	"Checked out items", "Objets empruntés",
	"Waiting approval", "En attente d&apos;approbation",
	"Logged in successfully.", "Connecté avec succès.",
	"Logged in successfully. Your last login was on ", "Connecté avec succès. Votre dernière connexion remonte au ",
	# Table headers
	"ID", "ID",
	"Title", "Titre",
	"Status", "Statut",
	"Last modified", "Modification",
	"High", "Important",
	"Low", "Bas",
	"Normal", "Normal",
	"Task", "Tâche",
	"Due by", "Attendu",
	"Completion", "Achèvement",
	"Completed", "Terminé",
	"Overdue", "En retard",
	"Type", "Type",
	"Name", "Nom",
	"Serial", "Num. de série",
	"File name", "Ficher",
	"File size", "Taille",
	"Uploaded by", "Téléchargé par",
	"Date", "Date",
	"Hits", "Nombre",
	"Download link", "Lien de téléchargement",
	"IP address", "Adresse IP",
	"Schedule", "Horaire",
	"Last run time", "Dernière execution",
	"Last result", "Dernier résultat",
	"Module", "Module",
	"Event", "Événement",
	"Email", "Email",
	"Level", "Niveau",
	"Last login", "Dernière connexion",
	# Settings
	"<p>You are logged in as <b>", "<p>Vous êtes connecté sous <b>",
	"</b> and your access level is <b>", "</b> et votre niveau d'accès est <b>",
	"<p>You have spent a total of <b>", "<p>Vous avez passé un total de <b>",
	"</b> hours on tickets.</p>", "</b> heures sur des billets.</p>",
	"Your email is not yet confirmed. Please enter the confirmation code here:", "Votre email n'est pas encore confirmé. S'il vous plaît entrez le code de confirmation:",
	"Email notifications are disabled.", "Les notifications email sont désactivées.",
	"Change your email", "Changer votre email",
	"To change your notification email address, enter a new address here. Leave empty to disable notifications:", "Pour changer votre adresse email de notification, entrez une nouvelle adresse ici. Laisser vide pour désactiver les notifications:",
	"Must be a valid email.", "Doit être une adresse email valide.",
	"Email address", "Adresse email",
	"Change email", "Change email",
	"Change your language", "Changer votre langue",
	"Select your language:", "Entrez votre langue:",
	"Change language", "Changer langue",
	"Change your password", "Changer votre mot de passe",
	"<p>Password management is synchronized with Active Directory.</p>", "<p>La gestion des mots de passe est synchronisé avec Active Directory.</p>",
	"<p>The demo account cannot change its password.</p>", "<p>Le compte démo ne peut pas changer son mot de passe.</p>",
	"Current password", "Mot de passe actuel",
	"New password", "Nouveau mot de passe",
	"Passwords do not match.", "Les mots de passe ne correspondent pas.",
	"Change password", "Changer mot de passe",
	"Email address confirmed. Press <a href='.'>here</a> to continue.", "Adresse email confirmée. Appuyez <a href='.'>ici</a> pour continuer.",
	"Confirmation code not found. Please go back and try again.", "Code de confirmation non trouvé. S'il vous plaît revenir en arrière et essayer à nouveau.",
	"Email address updated. Press <a href='.'>here</a> to continue.", "Adresse email mise à jour. Appuyez <a href='.'>ici</a> pour continuer.",
	"Password changed. Press <a href='.'>here</a> to go back home.", "Mot de passe changé. Appuyez <a href href='.'>ici</a> pour revenir à l'acceuil.",
	# Users
	"You have now logged out. Press <a href='.'>here</a> to go back to the login page.", "Vous êtes déconnecté. Appuyez <a href='.'>ici</a> pour revenir à la page de connexion.",
	"Invalid access level. Please go back and try again.", "Niveau d'accès non valide. S'il vous plaît revenir en arrière et essayer à nouveau.",
	"Updated access level for user <b>", "Niveau d'accès Mise à jour pour l'utilisateur",
	"</b>. Press <a href='./?m=users'>here</a> to continue.", "</b>. Appuyez <a href='./?m=users'>ici</a> pour continuer.",
	"Level change: ", "Changement de niveau: ",
	"Select a new access level for user <b>", "Sélectionnez un nouveau niveau d'accès pour l'utilisateur <b>",
	"<p>Here is a list of available NodePoint levels:</p>", "<p>Voici une liste des niveaux NodePoint disponibles:</p>",
	"Can change basic NodePoint settings", "Modifier les paramètres de base de NodePoint",
	"Can manage users, reset passwords, edit clients", "Gérer les utilisateurs, les mots de passe et modifier les clients",
	"Can add, retire and edit ", "Ajouter , retirer et modifier les ",
	"s, edit articles and items", "s, modifier les articles et objets",
	"Can create ", "Créer les ",
	"s, update tickets, track time", "s, modifier les billets, suivre le temps", 
	"Can view restricted tickets and ", "Afficher les billets privés et ", 
	"Can create tickets and comments",  "Créer des billets et commentaires",
	"Can view private tickets", "Afficher billets privés",
	"Password reset for user <b>", "Réinitialisation du mot de passe pour l'utilisateur <b>",
	"</b>. The new password is <b>", "</b> effectué. Le nouveau mot de passe est <b>",
	"</b>. Press <a href='./?m=users'>here</a> to continue.", "</b>. Appuyez <a href='./?m=users'>ici</a> pour continuer.",
	"Add a new user:", "Ajouter un nouvel utilisateur",
	"Passwords do not match. Please go back and try again.", "Les mots de passe ne correspondent pas. S'il vous plaît revenir en arrière et essayer à nouveau.",
	"This user name is reserved. Please go back and try again.", "Ce nom d'utilisateur est réservé. S'il vous plaît revenir en arrière et essayer à nouveau.",
	"User names should be between 3 and 20 characters, passwords should be at least 6 characters, emails less than 99 characters. Please go back and try again.", "Les noms d'utilisateur doit être comprise entre 3 et 20 caractères, mots de passe doivent comporter au moins 6 caractères, emails de moins de 99 caractères. S'il vous plaît revenir en arrière et essayer à nouveau.",
	"User <b>", "Utilisateur <b>",
	"</b> added. Press <a href='./?m=users'>here</a> to continue.", "</b> ajouté. Appuyez <a href='./?m=users'>ici</a> pour continuer.",
	"</b> added. Press <a href='.'>here</a> to go to the login page.", "</b> ajouté. Appuyez <a href='.'>ici</a> pour aller à la page de connexion.",
	"User already exists. Please go back and try again.", "L'utilisateur existe déjà. S'il vous plaît revenir en arrière et essayer à nouveau.",
	# Files
	"File not found or corrupted.", "Fichier introuvable ou corrompu.",
	"File size is larger than accepted value.", "La taille du fichier est plus grande que la valeur acceptée.",
	"File <b>", "Fichier <b>",
	"</b> uploaded.", "</b> téléchargé.",
	"File uploading to <b>", "Téléchargement vers <b>",
	"</b> failed.", "</b> a échoué.",
	"Add a new file", "Ajouter un nouveau fichier",
	"Available files", "Fichiers disponibles",
	"Access log", "Journal d'accès",
	"Select a file", "Sélectionner un fichier",
	# Items
	"Require checkout approval", "Demande approbation",
	"Desktop", "Ordinateur de bureau",
	"Laptop", "Portable",
	"Server", "Serveur",
	"Keyboard", "Clavier",
	"Mouse", "Souris",
	"Display", "Écran",
	"Phone", "Téléphone",
	"Software", "Logiciel",
	"Printer", "Imprimante",
	"Peripheral", "Périphérique",
	"Furniture", "Meuble",
	"Tool", "Outil",
	"Other", "Autre",
	# Buttons
	"Post", "Poster",
	"Save", "Sauvegarder",
	"Confirm", "Confirmer",
	"Upload", "Télécharger",
	"Clear log", "Effacer le journal",
	"Reset modules", "Réinitialiser les modules",
	"Add user", "Add user",
);

sub lang()
{
	my ($m, $l) = @_;
	if($l eq "FR") { return %FR; }
	#if($l eq "BR") { return %TMPL; }
	return %EN;
}