#!/usr/bin/perl
#
# NodePoint - (C) 2015 Patrick Lambert - http://nodepoint.ca
# Provided under the MIT License
#
# To use on Windows: Change all 'Linux' for 'Win32' in this file.
# To compile into a binary: Use PerlApp with the .perlapp file.
#
package nodepointlc;

# To add a locale:
# - Copy %TMPL to the language you want to add, for example %DE.
# - Each line contains 2 quoted strings. Translate the one on the left to the right.
# - Do not modify the left strings in any way.
# - Do not use any quotes (" or ')
# - Try to match the punctuation and capitalization as best you can.
# - Add the new language in the lang() function at the bottom.
# - Add the new language to 3 locations in nodepoint.pl (look for 'Default language' and 'Change your language').

%TMPL =
(
	# Tabs
	"Home", "",
	"Product", "",
	"Release", "",
	"Model", "",
	"Project", "",
	"Goal", "",
	"Milestone", "",
	"Resource", "",
	"Location", "",
	"Update", "",
	"Application", "",
	"Platform", "",
	"Version", "",
	"Asset", "",
	"Type", "",
	"Instance", "",
	"Tickets", "",
	"Articles", "",
	"Items", "",
	"Clients", "",
	"Settings", "",
	"Statistics", "",
	"Files", "",
	"Automation", "",
	"Custom forms", "",
	"Users management", "",
	"System log", "",
	"Logout", "",
	"Ticket ID", "",
	"Open", "",
	"Guest", "",
	"Login", "",
	"Tools", "",
	# Messages
	"Error", "",
	"Info", "",
	"Success", "",
	"Warning", "",
	# Login page
	"Enter your ", "",
	" credentials.", "",
	"User name must be between 2 and 20 characters.", "",
	"User name", "",
	"Password", "",
	"Register a new account", "",
	"Passwords do not match.", "",
	"Email (optional)", "",
	"Register", "",
	"Forgot your password?", "",
	"Must be a valid email.", "",
	"Please fill out this field.", "",
	"Confirm", "",
	# Automation descriptions
	"This module allows you to backup the database along with the uploads folder to another location for safe keeping. The folder must be a local or network path, and the type of backup can be a single archive file or a series of time stamped files.", "",
	"This module can fetch emails from an IMAP account and turn them into tickets automatically. The mail server and inbox information must be provided in order to log in, along with information about the ticket to create, and whether to delete the email afterward.", "",
	"This module will export a specific table to a file location automatically in CSV format. Specify the full path of a local file and the table to export.", "",
	"This module can keep the internal users list in sync with your Active Directory server. This requires credentials of a user with object listing rights. The Base DN should be the OU where your users are kept, and the filter can be used to filter specific object types. Emails can optionally be updated for all users as well.", "",
	"This module will list computer objects from your Active Directory server and create entries in the Inventory Control component. The Base DN should be the OU where your computers are kept. The serial will be set to the machine's hostname. This requires credentials of a user with object listing rights.", "",
	"This module interacts with active tickets that were modified more than x days ago. It can notify assigned users, and close the ticket.", "",
	"This module can remove files uploaded using the Files component after a set amount of days.", "",
	"This module will notify users about expired items checked out, overdue tasks and tickets requiring attention.", "",
	"This module can import CMDB data from a ServiceNow instance and import the data into the Inventory Control component. You need to enter valid credentials and the name of the table to read, along with the table header mappings.", "",
	"This module will dynamically update the MOTD from a text file.", "",
	# Notifications
	"This is an automated message from ", "",
	"To disable notifications, log into your account and remove the email under Settings.", "",
	"Could not send notification email to ", "",
	", target email was rejected.", "",
	", connection to SMTP server failed.", "",
	# Home page
	"There are ", "",
	" items awaiting checkout approval. Press <a href='./?m=items'>here</a> to view the list.", "",
	"Clear", "",
	"Ticket", "",
	"requires your attention.", "",
	"Getting started", "",
	"<p>Use the <b>", "",
	"s</b> tab to browse available ", "",
	"s along with their ", "",
	"s. You can view basic information about them and see their description.", "",
	" Use the <b>Tickets</b> tab to browse current tickets and comments.", "",
	" The <b>Articles</b> tab contains related support articles.", "",
	" The <b>Items</b> tab contains inventory items you can checkout.", "",
	" The <b>Clients</b> tab contains a list of contacts.", "",
	" You can also change your email address and password under the <b>Settings</b> tab.</p>", "",
	"Your current access level is", "",
	"<p>Your email address is not currently confirmed. Make sure you go to the Settings tab to enter your confirmation code. You can also change your email address if you did not receive your confirmation email.</p>", "",
	"Shoutbox", "",
	"Type your message here", "",
	"Tickets you created", "",
	"Tickets you follow", "",
	"Tickets assigned to you", "",
	"Tasks assigned to you", "",
	"Subscribed articles", "",
	"Checked out items", "",
	"Waiting approval", "",
	# Table headers
	"ID", "",
	"Title", "",
	"Status", "",
	"Last modified", "",
	"High", "",
	"Low", "",
	"Normal", "",
	"Task", "",
	"Due by", "",
	"Completion", "",
	"Completed", "",
	"Overdue", "",
	"Type", "",
	"Name", "",
	"Serial", "",
	
	# Buttons
	"Post", "",
	"Save", "",
);

%EN =
(
	# Tabs
	"Home", "Home",
	"Product", "Product",
	"Release", "Release",
	"Model", "Model",
	"Project", "Project",
	"Goal", "Goal",
	"Milestone", "Milestone",
	"Resource", "Resource",
	"Location", "Location",
	"Update", "Update",
	"Application", "Application",
	"Platform", "Platform",
	"Version", "Version",
	"Asset", "Asset",
	"Type", "Type",
	"Instance", "Instance",
	"Tickets", "Tickets",
	"Articles", "Articles",
	"Items", "Items",
	"Clients", "Clients",
	"Settings", "Settings",
	"Statistics", "Statistics",
	"Files", "Files",
	"Automation", "Automation",
	"Custom forms", "Custom forms",
	"Users management", "Users management",
	"System log", "System log",
	"Logout", "Logout",
	"Ticket ID", "Ticket ID",
	"Open", "Open",
	"Guest", "Guest",
	"Login", "Login",
	"Tools", "Tools",
	# Messages
	"Error", "Error",
	"Info", "Info",
	"Success", "Success",
	"Warning", "Warning",
	# Login page
	"Enter your ", "Enter your ",
	" credentials.", " credentials.",
	"User name must be between 2 and 20 characters.", "User name must be between 2 and 20 characters.",
	"User name", "User name",
	"Password", "Password",
	"Register a new account", "Register a new account",
	"Passwords do not match.", "Passwords do not match.",
	"Email (optional)", "Email (optional)",
	"Register", "Register",
	"Forgot your password?", "Forgot your password?",
	"Must be a valid email.", "Must be a valid email.",
	"Please fill out this field.", "Please fill out this field.",
	"Confirm", "Confirm",
	# Automation descriptions
	"This module allows you to backup the database along with the uploads folder to another location for safe keeping. The folder must be a local or network path, and the type of backup can be a single archive file or a series of time stamped files.", "This module allows you to backup the database along with the uploads folder to another location for safe keeping. The folder must be a local or network path, and the type of backup can be a single archive file or a series of time stamped files.",
	"This module can fetch emails from an IMAP account and turn them into tickets automatically. The mail server and inbox information must be provided in order to log in, along with information about the ticket to create, and whether to delete the email afterward.", "This module can fetch emails from an IMAP account and turn them into tickets automatically. The mail server and inbox information must be provided in order to log in, along with information about the ticket to create, and whether to delete the email afterward.",
	"This module will export a specific table to a file location automatically in CSV format. Specify the full path of a local file and the table to export.", "This module will export a specific table to a file location automatically in CSV format. Specify the full path of a local file and the table to export.",
	"This module can keep the internal users list in sync with your Active Directory server. This requires credentials of a user with object listing rights. The Base DN should be the OU where your users are kept, and the filter can be used to filter specific object types. Emails can optionally be updated for all users as well.", "This module can keep the internal users list in sync with your Active Directory server. This requires credentials of a user with object listing rights. The Base DN should be the OU where your users are kept, and the filter can be used to filter specific object types. Emails can optionally be updated for all users as well.",
	"This module will list computer objects from your Active Directory server and create entries in the Inventory Control component. The Base DN should be the OU where your computers are kept. The serial will be set to the machine's hostname. This requires credentials of a user with object listing rights.", "This module will list computer objects from your Active Directory server and create entries in the Inventory Control component. The Base DN should be the OU where your computers are kept. The serial will be set to the machine's hostname. This requires credentials of a user with object listing rights.",
	"This module interacts with active tickets that were modified more than x days ago. It can notify assigned users, and close the ticket.", "This module interacts with active tickets that were modified more than x days ago. It can notify assigned users, and close the ticket.",
	"This module can remove files uploaded using the Files component after a set amount of days.", "This module can remove files uploaded using the Files component after a set amount of days.",
	"This module will notify users about expired items checked out, overdue tasks and tickets requiring attention.", "This module will notify users about expired items checked out, overdue tasks and tickets requiring attention.",
	"This module can import CMDB data from a ServiceNow instance and import the data into the Inventory Control component. You need to enter valid credentials and the name of the table to read, along with the table header mappings.", "This module can import CMDB data from a ServiceNow instance and import the data into the Inventory Control component. You need to enter valid credentials and the name of the table to read, along with the table header mappings.",
	"This module will dynamically update the MOTD from a text file.", "This module will dynamically update the MOTD from a text file.",
	# Notifications
	"This is an automated message from ", "This is an automated message from ",
	"To disable notifications, log into your account and remove the email under Settings.", "To disable notifications, log into your account and remove the email under Settings.",
	"Could not send notification email to ", "Could not send notification email to ",
	", target email was rejected.", ", target email was rejected.",
	", connection to SMTP server failed.", ", connection to SMTP server failed.",
	# Home page
	"There are ", "There are ",
	" items awaiting checkout approval. Press <a href='./?m=items'>here</a> to view the list.", " items awaiting checkout approval. Press <a href='./?m=items'>here</a> to view the list.",
	"Clear", "Clear",
	"Ticket", "Ticket",
	"requires your attention.", "requires your attention.",
	"Getting started", "Getting started",
	"<p>Use the <b>", "<p>Use the <b>",
	"s</b> tab to browse available ", "s</b> tab to browse available ",
	"s along with their ", "s along with their ",
	"s. You can view basic information about them and see their description.", "s. You can view basic information about them and see their description.",
	" Use the <b>Tickets</b> tab to browse current tickets and comments.", " Use the <b>Tickets</b> tab to browse current tickets and comments.",
	" The <b>Articles</b> tab contains related support articles.", " The <b>Articles</b> tab contains related support articles.",
	" The <b>Items</b> tab contains inventory items you can checkout.", " The <b>Items</b> tab contains inventory items you can checkout.",
	" The <b>Clients</b> tab contains a list of contacts.", " The <b>Clients</b> tab contains a list of contacts.",
	" You can also change your email address and password under the <b>Settings</b> tab.</p>", " You can also change your email address and password under the <b>Settings</b> tab.</p>",
	"Your current access level is", "Your current access level is",
	"<p>Your email address is not currently confirmed. Make sure you go to the Settings tab to enter your confirmation code. You can also change your email address if you did not receive your confirmation email.</p>", "<p>Your email address is not currently confirmed. Make sure you go to the Settings tab to enter your confirmation code. You can also change your email address if you did not receive your confirmation email.</p>",
	"Shoutbox", "Shoutbox",
	"Type your message here", "Type your message here",
	"Tickets you created", "Tickets you created",
	"Tickets you follow", "Tickets you follow",
	"Tickets assigned to you", "Tickets assigned to you",
	"Tasks assigned to you", "Tasks assigned to you",
	"Subscribed articles", "Subscribed articles",
	"Checked out items", "Checked out items",
	"Waiting approval", "Waiting approval",
	# Table headers
	"ID", "ID",
	"Title", "Title",
	"Status", "Status",
	"Last modified", "Last modified",
	"High", "High",
	"Low", "Low",
	"Normal", "Normal",
	"Task", "Task",
	"Due by", "Due by",
	"Completion", "Completion",
	"Completed", "Completed",
	"Overdue", "Overdue",
	"Type", "Type",
	"Name", "Name",
	"Serial", "Serial",
	 
	# Buttons
	"Post", "Post",
	"Save", "Save",
	
);

%FR =
(
	# Tabs
	"Home", "Accueil",
	"Product", "Produit",
	"Release", "Version",
	"Model", "Modèle",
	"Project", "Projet",
	"Goal", "Objectif",
	"Milestone", "Étape",
	"Resource", "Ressource",
	"Location", "Emplacement",
	"Update", "Mise à jour",
	"Application", "Application",
	"Platform", "Plate-forme",
	"Version", "Version",
	"Asset", "Atout",
	"Type", "Genre",
	"Instance", "Article",
	"Tickets", "Billets",
	"Articles", "Articles",
	"Items", "Objets",
	"Clients", "Clients",
	"Settings", "Préférences",
	"Statistics", "Statistiques",
	"Files", "Fichiers",
	"Automation", "Automatisation",
	"Custom forms", "Formulaires personnalisés",
	"Users management", "Utilisateurs",
	"System log", "Journal du système",
	"Logout", "Se déconnecter",
	"Ticket ID", "Billet ID",
	"Open", "Ouvrir",
	"Guest", "Invité",
	"Login", "Identification",
	"Tools", "Outils",
	# Messages
	"Error", "Erreur",
	"Info", "Info",
	"Success", "Succès",
	"Warning", "Attention",
	# Login page
	"Enter your ", "Entrez vos informations d&apos;identification pour ",
	" credentials.", ".",
	"User name must be between 2 and 20 characters.", "Nom d&apos;utilisateur doit être entre 2 et 20 caractères.",
	"User name", "Nom d&apos;utilisateur",
	"Password", "Mot de passe",
	"Register a new account", "Créer un nouveau compte",
	"Passwords do not match.", "Les mots de passe ne correspondent pas.",
	"Email (optional)", "Email (facultatif)",
	"Register", "Créer",
	"Forgot your password?", "Mot de passe oublié?",
	"Must be a valid email.", "Doit être une adresse email valide",
	"Please fill out this field.", "S&apos;il vous plaît remplir ce champ",
	"Confirm", "Confirmation",
	# Automation descriptions
	"This module allows you to backup the database along with the uploads folder to another location for safe keeping. The folder must be a local or network path, and the type of backup can be a single archive file or a series of time stamped files.", "Ce module vous permet de sauvegarder la base de données ainsi que le dossier de fichiers vers un autre emplacement. Le dossier doit être un chemin local ou réseau, et le type de sauvegarde peut être un seul fichier d'archive ou une série de fichiers horodatés.",
	"This module can fetch emails from an IMAP account and turn them into tickets automatically. The mail server and inbox information must be provided in order to log in, along with information about the ticket to create, and whether to delete the email afterward.", "Ce module peut aller chercher des emails à partir d'un compte IMAP et les transforme en billets automatiquement. Les informations du serveur de messagerie et boîte de réception doivent être fournis afin de se connecter, avec les informations sur les billets de créer.",
	"This module will export a specific table to a file location automatically in CSV format. Specify the full path of a local file and the table to export.", "Ce module va exporter une table spécifique à un emplacement de fichier automatiquement en format CSV. Indiquez le chemin complet d'un fichier local et la table à exporter.",
	"This module can keep the internal users list in sync with your Active Directory server. This requires credentials of a user with object listing rights. The Base DN should be the OU where your users are kept, and the filter can be used to filter specific object types. Emails can optionally be updated for all users as well.", "Ce module peut garder la liste des utilisateurs internes en phase avec votre serveur Active Directory. Cela nécessite les informations d'identification d'un utilisateur avec la permission d'énumérer les objets. Le DN de base doit être l'unité d'organisation où vos utilisateurs sont conservées, et le filtre peut être utilisé pour filtrer un spécifique type d'objets. les emails peuvent aussi être mis à jour pour tous les utilisateurs.",
	"This module will list computer objects from your Active Directory server and create entries in the Inventory Control component. The Base DN should be the OU where your computers are kept. The serial will be set to the machine's hostname. This requires credentials of a user with object listing rights.", "Ce module liste des objets ordinateur à partir de votre serveur Active Directory et crée des entrées dans le composant de gestion des objets. Le DN de base doit être l'unité d'organisation où vos ordinateurs sont conservés. Le numéro de série sera réglé sur le nom d'hôte de la machine. Cela nécessite les informations d'identification d'un utilisateur avec la permission d'énumérer les objets.",
	"This module interacts with active tickets that were modified more than x days ago. It can notify assigned users, and close the ticket.", "Ce module interagit avec billets actifs qui ont été modifiés il y a plus x jours. Il peut avertir les utilisateurs affectés, et fermer le billet.",
	"This module can remove files uploaded using the Files component after a set amount of days.", "Ce module peut supprimer les fichiers téléchargés en utilisant le composant Fichiers après un certain laps de jours.",
	"This module will notify users about expired items checked out, overdue tasks and tickets requiring attention.", "Ce module informera les utilisateurs sur les produits périmés, les tâches et les billets en retard nécessitant une attention particulière.",
	"This module can import CMDB data from a ServiceNow instance and import the data into the Inventory Control component. You need to enter valid credentials and the name of the table to read, along with the table header mappings.", "Ce module peut importer des données CMDB d'une instance ServiceNow et importer les données dans le composant de gestion des objets. Vous devez entrer les informations d'identification valides et le nom de la table à lire, avec l'en-tête de table correspondantes.",
	"This module will dynamically update the MOTD from a text file.", "Ce module va mettre à jour dynamiquement le MOTD à partir d'un fichier texte.",
	# Notifications
	"This is an automated message from ", "Ceci est un message automatique de ",
	"To disable notifications, log into your account and remove the email under Settings.", "Pour désactiver les notifications, connectez-vous à votre compte et supprimer l&apos;email sous Paramètres.",
	"Could not send notification email to ", "Impossible d'envoyer une notification email à ",
	", target email was rejected.", ", le email a été rejeté.",
	", connection to SMTP server failed.", ", la connexion au serveur SMTP a échoué.",
	# Home page
	"There are ", "Il y a ",
	" items awaiting checkout approval. Press <a href='./?m=items'>here</a> to view the list.", " objets en attente d&apos;approbation. Appuyez <a href='./?m=items'>ici</a> pour afficher la liste.",
	"Clear", "Enlever",
	"Ticket", "Billet",
	"requires your attention.", "exige votre attention.",
	"Getting started", "Message de bienvenue",
	"<p>Use the <b>", "<p>Utilisez l&apos;onglet <b>",
	"s</b> tab to browse available ", "s</b> pour voir les ",
	"s along with their ", "s avec leurs ",
	"s. You can view basic information about them and see their description.", "s. Vous pouvez afficher des informations de base sur eux et voir leur description.",
	" Use the <b>Tickets</b> tab to browse current tickets and comments.", " Utilisez l&apos;onglet <b>Billets</b> pour parcourir les billets et commentaires.",
	" The <b>Articles</b> tab contains related support articles.", " L&apos;onglet <b>Articles</b> contient des articles connexes de soutien.",
	" The <b>Items</b> tab contains inventory items you can checkout.", " L&apos;onglet <b>Objets</b> contient des éléments d'inventaire que vous pouvez demander.",
	" The <b>Clients</b> tab contains a list of contacts.", " L&apos;onglet <b>Clients</b> contient la liste des contacts.",
	" You can also change your email address and password under the <b>Settings</b> tab.</p>", " Vous pouvez également modifier votre adresse email et mot de passe dans <b>Paramètres</b>.</p>",
	"Your current access level is", "Votre niveau d&apos;accès actuel est",
	"<p>Your email address is not currently confirmed. Make sure you go to the Settings tab to enter your confirmation code. You can also change your email address if you did not receive your confirmation email.</p>", "<p>Votre adresse de messagerie n&apos;est pas confirmée. Assurez-vous que vous allez à l'onglet Paramètres pour entrer votre code de confirmation. Vous pouvez également modifier votre adresse email si vous ne recevez pas votre courriel de confirmation.</p>",
	"Shoutbox", "Shoutbox",
	"Type your message here", "Entrez votre message ici",
	"Tickets you created", "Billets que vous avez créé",
	"Tickets you follow", "Billets suivies",
	"Tickets assigned to you", "Billets qui vous sont assignées",
	"Tasks assigned to you", "Tâches qui vous sont assignées",
	"Subscribed articles", "Articles souscrit",
	"Checked out items", "Objets empruntés",
	"Waiting approval", "En attente d&apos;approbation",
	# Table headers
	"ID", "ID",
	"Title", "Titre",
	"Status", "Statut",
	"Last modified", "Modification",
	"High", "Important",
	"Low", "Bas",
	"Normal", "Normal",
	"Task", "Tâche",
	"Due by", "Attendu",
	"Completion", "Achèvement",
	"Completed", "Terminé",
	"Overdue", "En retard",
	"Type", "Type",
	"Name", "Nom",
	"Serial", "Num. de série",
	
	# Buttons
	"Post", "Poster",
	"Save", "Sauvegarder",
	
);

sub lang()
{
	my ($m, $l) = @_;
	if($l eq "FR") { return %FR; }
	#if($l eq "BR") { return %TMPL; }
	return %EN;
}